package formularios;

import dao.DaoDesempeño;
import dao.DaoProyecto;
import dao.DaoTrabajador;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andreita
 */
public class FrmDesempeño extends javax.swing.JFrame {
    private DaoDesempeño daoD = new DaoDesempeño();
    private DaoTrabajador daoT = new DaoTrabajador();
    private DaoProyecto daoP = new DaoProyecto();
    private int posActualTrab = 0;
    private int posActualProy = 0;
    private int IdDesempeño = 0;
    private String numCedula = "";
    private boolean esNuevo;
    
    /**
     * Creates new form FrmDesempeño
     */
    public FrmDesempeño() {
        initComponents();
        mostrarEnTF(0, 0);
    }
    public void setDao(DaoDesempeño daoD, DaoTrabajador daoT, DaoProyecto daoP){
        this.daoD = daoD;
        this.daoT = daoT;
        this.daoP = daoP;
    }
    
    private void mostrarEnTF(int fila1 , int fila2){
       if(!daoT.getListaTrabajador().isEmpty() && !daoP.getListaProyecto().isEmpty()){
            
            numCedula = daoT.getListaTrabajador().get(fila1).getNumCedula();
            int IdDesempeño = daoD.getListaDesempeño().get(fila2).getIdDesempeño();
            int IdProyecto = daoP.getListaProyecto().get(fila2).getIdProyecto();
            
            LbIdDesempeño.setText("" + IdDesempeño);
            LbIdProyecto.setText("" + IdProyecto);
            LbNumCedula.setText("" + numCedula);
            esNuevo=false;
            
            
            if(daoD.buscarDesempeño(numCedula, IdProyecto) != null ){
                LbIdDesempeño.setText("" + daoD.buscarDesempeño(numCedula, IdProyecto).getIdDesempeño());
                IdDesempeño = Integer.parseInt(LbIdDesempeño.getText());
                TfPuesto.setText(daoD.buscarDesempeño(numCedula, IdProyecto).getPuesto());
                TfCalificacion.setText("" + daoD.buscarDesempeño(numCedula, IdProyecto).getCalificacion());
                TfSalario.setText("" + daoD.buscarDesempeño(numCedula, IdProyecto).getSalario());
                TfFechaI.setText(daoD.buscarDesempeño(numCedula, IdProyecto).getFechaIngreso());
                TfFechaS.setText(daoD.buscarDesempeño(numCedula, IdProyecto).getFechaSalida());
                TfRazon.setText(daoD.buscarDesempeño(numCedula, IdProyecto).getRazonSalida());
            }
            else{
                limpiar();
            }
            
            

            int ultReg1 = daoT.getListaTrabajador().size();
            int ultReg2 = daoP.getListaProyecto().size();
            
            LbContadorT.setText("" + (fila1 + 1) + " de " + ultReg1);
            LbContadorP.setText("" + (fila2 + 1) + " de " + ultReg2);
            
            TfPuesto.requestFocus();
        }else{
             limpiar();
        }
    }
    /**
     * Limpia los textFields
     */
    private void limpiar(){
        esNuevo = true;
        LbIdDesempeño.setText("");
        TfPuesto.setText("");
        TfCalificacion.setText("");
        TfSalario.setText("");
        TfRazon.setText("");
        TfFechaI.setText("");
        TfFechaS.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LbDesempeño = new javax.swing.JLabel();
        LbProyecto = new javax.swing.JLabel();
        LbNumC = new javax.swing.JLabel();
        LbPuesto = new javax.swing.JLabel();
        LbSalario = new javax.swing.JLabel();
        LBFechaIngreso = new javax.swing.JLabel();
        LbFechaSalida = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TfFechaS = new javax.swing.JTextField();
        CbNotas = new javax.swing.JComboBox<>();
        btnMostarNota = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        btnProyAnterior = new javax.swing.JButton();
        LbContadorP = new javax.swing.JLabel();
        btnSiguienteProy = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jToolBar3 = new javax.swing.JToolBar();
        btnTrabAnterior = new javax.swing.JButton();
        LbContadorT = new javax.swing.JLabel();
        btnSiguienteTrab = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jToolBar4 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEliminar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnGuardar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnActualizarBD = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JSeparator();
        LbIdProyecto = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        LbIdDesempeño = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        LbNumCedula = new javax.swing.JLabel();
        TfPuesto = new javax.swing.JTextField();
        TfCalificacion = new javax.swing.JTextField();
        TfSalario = new javax.swing.JTextField();
        TfFechaI = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TfRazon = new javax.swing.JTextArea();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DESEMPEÑO");
        setLocation(new java.awt.Point(1100, 710));
        setMaximumSize(new java.awt.Dimension(1100, 710));
        setMinimumSize(new java.awt.Dimension(1100, 710));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRISMA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 200, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/prisma-logo-3805665B69-seeklogo.com.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/70-709970_fondo-morado-oscuro-hd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 710));

        jPanel1.setBackground(new java.awt.Color(16, 16, 16));
        jPanel1.setForeground(new java.awt.Color(16, 16, 16));
        jPanel1.setMaximumSize(new java.awt.Dimension(1050, 630));

        LbDesempeño.setBackground(new java.awt.Color(16, 16, 16));
        LbDesempeño.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbDesempeño.setForeground(new java.awt.Color(255, 255, 255));
        LbDesempeño.setText("Id Desempeño:");

        LbProyecto.setBackground(new java.awt.Color(16, 16, 16));
        LbProyecto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbProyecto.setForeground(new java.awt.Color(255, 255, 255));
        LbProyecto.setText("Id Proyecto:");

        LbNumC.setBackground(new java.awt.Color(16, 16, 16));
        LbNumC.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbNumC.setForeground(new java.awt.Color(255, 255, 255));
        LbNumC.setText("N° de Cédula:");

        LbPuesto.setBackground(new java.awt.Color(16, 16, 16));
        LbPuesto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbPuesto.setForeground(new java.awt.Color(255, 255, 255));
        LbPuesto.setText("Puesto:");

        LbSalario.setBackground(new java.awt.Color(16, 16, 16));
        LbSalario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbSalario.setForeground(new java.awt.Color(255, 255, 255));
        LbSalario.setText("Salario:");

        LBFechaIngreso.setBackground(new java.awt.Color(16, 16, 16));
        LBFechaIngreso.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LBFechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        LBFechaIngreso.setText("Fecha de Ingreso:");

        LbFechaSalida.setBackground(new java.awt.Color(16, 16, 16));
        LbFechaSalida.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbFechaSalida.setForeground(new java.awt.Color(255, 255, 255));
        LbFechaSalida.setText("Fecha de Salida:");

        jLabel12.setBackground(new java.awt.Color(16, 16, 16));
        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nota Disciplinaria:");

        TfFechaS.setBackground(new java.awt.Color(16, 16, 16));
        TfFechaS.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfFechaS.setForeground(new java.awt.Color(78, 34, 88));
        TfFechaS.setBorder(null);
        TfFechaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfFechaSActionPerformed(evt);
            }
        });

        CbNotas.setBackground(new java.awt.Color(78, 34, 88));
        CbNotas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbNotas.setForeground(new java.awt.Color(255, 255, 255));
        CbNotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nota 1", "Nota 2", "Nota 3" }));
        CbNotas.setBorder(null);

        btnMostarNota.setBackground(new java.awt.Color(78, 34, 88));
        btnMostarNota.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnMostarNota.setForeground(new java.awt.Color(255, 255, 255));
        btnMostarNota.setText("Mostrar Nota");
        btnMostarNota.setBorder(null);
        btnMostarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarNotaActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(16, 16, 16));
        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Calificación: ");

        btnVolver.setBackground(new java.awt.Color(16, 16, 16));
        btnVolver.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/anterior (1).png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jToolBar2.setBackground(new java.awt.Color(16, 16, 16));
        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setRollover(true);

        btnProyAnterior.setBackground(new java.awt.Color(16, 16, 16));
        btnProyAnterior.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnProyAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnProyAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/anterior (1).png"))); // NOI18N
        btnProyAnterior.setText("Anterior P");
        btnProyAnterior.setFocusable(false);
        btnProyAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProyAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProyAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyAnteriorActionPerformed(evt);
            }
        });
        jToolBar2.add(btnProyAnterior);

        LbContadorP.setBackground(new java.awt.Color(16, 16, 16));
        LbContadorP.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        LbContadorP.setForeground(new java.awt.Color(255, 255, 255));
        LbContadorP.setText("0 de 0");
        jToolBar2.add(LbContadorP);

        btnSiguienteProy.setBackground(new java.awt.Color(16, 16, 16));
        btnSiguienteProy.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSiguienteProy.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteProy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/proximo.png"))); // NOI18N
        btnSiguienteProy.setText("Siguiente P");
        btnSiguienteProy.setFocusable(false);
        btnSiguienteProy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguienteProy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguienteProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteProyActionPerformed(evt);
            }
        });
        jToolBar2.add(btnSiguienteProy);
        jToolBar2.add(jSeparator8);

        jToolBar3.setBackground(new java.awt.Color(16, 16, 16));
        jToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar3.setRollover(true);

        btnTrabAnterior.setBackground(new java.awt.Color(16, 16, 16));
        btnTrabAnterior.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnTrabAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnTrabAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/flecha-izquierda.png"))); // NOI18N
        btnTrabAnterior.setText("Anterior T");
        btnTrabAnterior.setFocusable(false);
        btnTrabAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrabAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrabAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabAnteriorActionPerformed(evt);
            }
        });
        jToolBar3.add(btnTrabAnterior);

        LbContadorT.setBackground(new java.awt.Color(16, 16, 16));
        LbContadorT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        LbContadorT.setForeground(new java.awt.Color(255, 255, 255));
        LbContadorT.setText("0 de 0 ");
        jToolBar3.add(LbContadorT);

        btnSiguienteTrab.setBackground(new java.awt.Color(16, 16, 16));
        btnSiguienteTrab.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSiguienteTrab.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteTrab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/flecha-derecha.png"))); // NOI18N
        btnSiguienteTrab.setText("Siguiente T");
        btnSiguienteTrab.setFocusable(false);
        btnSiguienteTrab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguienteTrab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguienteTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteTrabActionPerformed(evt);
            }
        });
        jToolBar3.add(btnSiguienteTrab);
        jToolBar3.add(jSeparator7);

        jLabel14.setBackground(new java.awt.Color(16, 16, 16));
        jLabel14.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(78, 34, 88));
        jLabel14.setText("DESEMPEÑO");

        jSeparator5.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator5.setForeground(new java.awt.Color(78, 34, 88));

        jToolBar4.setBackground(new java.awt.Color(16, 16, 16));
        jToolBar4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar4.setRollover(true);

        btnNuevo.setBackground(new java.awt.Color(16, 16, 16));
        btnNuevo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/agregar-archivo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar4.add(btnNuevo);
        jToolBar4.add(jSeparator1);

        btnModificar.setBackground(new java.awt.Color(16, 16, 16));
        btnModificar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar4.add(btnModificar);
        jToolBar4.add(jSeparator2);

        btnEliminar.setBackground(new java.awt.Color(16, 16, 16));
        btnEliminar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/basura.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar4.add(btnEliminar);
        jToolBar4.add(jSeparator3);

        btnGuardar.setBackground(new java.awt.Color(16, 16, 16));
        btnGuardar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/disquete.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar4.add(btnGuardar);
        jToolBar4.add(jSeparator4);

        btnActualizarBD.setBackground(new java.awt.Color(16, 16, 16));
        btnActualizarBD.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnActualizarBD.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/actualizar.png"))); // NOI18N
        btnActualizarBD.setText("Actualizar BD");
        btnActualizarBD.setFocusable(false);
        btnActualizarBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarBD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBDActionPerformed(evt);
            }
        });
        jToolBar4.add(btnActualizarBD);
        jToolBar4.add(jSeparator6);

        jSeparator9.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator9.setForeground(new java.awt.Color(78, 34, 88));

        LbIdProyecto.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        LbIdProyecto.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator10.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator10.setForeground(new java.awt.Color(78, 34, 88));

        LbIdDesempeño.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        LbIdDesempeño.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator11.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator11.setForeground(new java.awt.Color(78, 34, 88));

        LbNumCedula.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        LbNumCedula.setForeground(new java.awt.Color(78, 34, 88));

        TfPuesto.setBackground(new java.awt.Color(16, 16, 16));
        TfPuesto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfPuesto.setForeground(new java.awt.Color(78, 34, 88));
        TfPuesto.setBorder(null);

        TfCalificacion.setBackground(new java.awt.Color(16, 16, 16));
        TfCalificacion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfCalificacion.setForeground(new java.awt.Color(78, 34, 88));
        TfCalificacion.setBorder(null);

        TfSalario.setBackground(new java.awt.Color(16, 16, 16));
        TfSalario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfSalario.setForeground(new java.awt.Color(78, 34, 88));
        TfSalario.setBorder(null);

        TfFechaI.setBackground(new java.awt.Color(16, 16, 16));
        TfFechaI.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfFechaI.setForeground(new java.awt.Color(78, 34, 88));
        TfFechaI.setBorder(null);
        TfFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfFechaIActionPerformed(evt);
            }
        });

        jSeparator12.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator12.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator13.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator13.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator14.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator14.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator15.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator15.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator16.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator16.setForeground(new java.awt.Color(78, 34, 88));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Razón de Salida:");

        TfRazon.setBackground(new java.awt.Color(16, 16, 16));
        TfRazon.setColumns(20);
        TfRazon.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfRazon.setForeground(new java.awt.Color(78, 34, 88));
        TfRazon.setRows(5);
        jScrollPane1.setViewportView(TfRazon);

        jSeparator17.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator17.setForeground(new java.awt.Color(78, 34, 88));

        jLabel6.setBackground(new java.awt.Color(78, 34, 88));
        jLabel6.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 34, 88));
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(78, 34, 88));
        jLabel8.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(78, 34, 88));
        jLabel8.setText("-");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(316, 316, 316)
                                .addComponent(LbSalario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(278, 278, 278)
                                .addComponent(LbProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbNumC)
                                .addGap(309, 309, 309)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbPuesto)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbFechaSalida)
                                .addGap(295, 295, 295)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(194, 194, 194)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(btnMostarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(CbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LBFechaIngreso)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(416, 416, 416)
                                .addComponent(TfFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnVolver)
                .addGap(148, 148, 148)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(LbIdDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(LbDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LbPuesto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(LbNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(LbSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMostarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(CbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TfFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(242, 242, 242)
                    .addComponent(LbIdDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(445, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 770, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBDActionPerformed
        // TODO add your handling code here:
        String msn1 = daoD.actualizarBD();
        String msn2 = daoT.actualizarBD();
        JOptionPane.showMessageDialog(this, msn1, "Desempeño: Actualizar Base de Datos",
                JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(this, msn2, "Trabajador: Actualizar Base de Datos",
                JOptionPane.INFORMATION_MESSAGE);
        posActualProy = 0;
        posActualTrab = 0;
        daoD = new DaoDesempeño();
        daoT = new DaoTrabajador();
        mostrarEnTF(posActualTrab, posActualProy);
    }//GEN-LAST:event_btnActualizarBDActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(TfPuesto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar el puesto", "Desempeño",
                JOptionPane.WARNING_MESSAGE);
            this.TfPuesto.requestFocus();
            return;
        }

        if(TfSalario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar el salario", "Desempeño",
                JOptionPane.WARNING_MESSAGE);
            this.TfSalario.requestFocus();
            return;
        }

        if(TfFechaI.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar la fecha de ingreso",
                "Desempeño", JOptionPane.WARNING_MESSAGE);
            this.TfFechaI.requestFocus();
            return;
        }

        int b;
        if(esNuevo){
            int mayor = daoD.buscarMayor();
            if(daoD.getListaDesempeño().isEmpty()){
                b = daoD.agregarDesempeño(
                        Double.parseDouble(TfCalificacion.getText()),
                        TfFechaI.getText(),
                        TfFechaS.getText(),
                        1,
                        TfPuesto.getText(),
                        TfRazon.getText(),
                        Double.parseDouble(TfSalario.getText()),
                        Integer.parseInt(LbIdProyecto.getText()),
                        LbNumCedula.getText());
                if(Double.parseDouble(TfCalificacion.getText()) < 6){
                    daoT.establecerInapropiado(LbNumCedula.getText());
                }
            }
            else{
                
                b = daoD.agregarDesempeño(
                        Double.parseDouble(TfCalificacion.getText()),
                        TfFechaI.getText(),
                        TfFechaS.getText(),
                        mayor + 1,
                        TfPuesto.getText(),
                        TfRazon.getText(),
                        Double.parseDouble(TfSalario.getText()),
                        Integer.parseInt(LbIdProyecto.getText()),
                        LbNumCedula.getText());
                if(Double.parseDouble(TfCalificacion.getText()) < 6){
                    daoT.establecerInapropiado(LbNumCedula.getText());
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Error: ya existe este registro",
                    "Desempeño",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(b == 1){
            JOptionPane.showMessageDialog(this, "Registro guardado...", "Desempeño",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        this.mostrarEnTF(0,0);
        limpiar();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this,
            "¿Realmente desea eliminar el Desempeño: " +
            this.LbIdDesempeño.getText()+ "?","Desempeño",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (resp == 0){
            int b = daoD.eliminarDesempeño(Integer.parseInt(LbIdDesempeño.getText()));
            if(b == 1){
                JOptionPane.showMessageDialog(this, "Registro eliminado satisfactoriamente",
                    "Desempeño", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error inesperado, verifique y vuelva intentar",
                    "Desempeño", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        FrmModificarD des = new FrmModificarD(daoD, daoT, daoP, IdDesempeño, numCedula);
        des.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.limpiar();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSiguienteTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteTrabActionPerformed
        // TODO add your handling code here:
        posActualTrab++;
        if (posActualTrab == daoT.getListaTrabajador().size()) posActualTrab = 0;
        this.mostrarEnTF(posActualTrab, posActualProy);
    }//GEN-LAST:event_btnSiguienteTrabActionPerformed

    private void btnTrabAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabAnteriorActionPerformed
        // TODO add your handling code here:
        if (posActualTrab == 0) posActualTrab = daoT.getListaTrabajador().size();
        posActualTrab--;
        this.mostrarEnTF(posActualTrab, posActualProy);
    }//GEN-LAST:event_btnTrabAnteriorActionPerformed

    private void btnSiguienteProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteProyActionPerformed
        // TODO add your handling code here:
        posActualProy++;
        if (posActualProy == daoP.getListaProyecto().size()) posActualProy = 0;
        this.mostrarEnTF(posActualTrab, posActualProy);
    }//GEN-LAST:event_btnSiguienteProyActionPerformed

    private void btnProyAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyAnteriorActionPerformed
        // TODO add your handling code here:
        if (posActualProy == 0) posActualProy = daoP.getListaProyecto().size();
        posActualProy--;
        this.mostrarEnTF(posActualTrab, posActualProy);
    }//GEN-LAST:event_btnProyAnteriorActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmInicio ini = new FrmInicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnMostarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarNotaActionPerformed
        // TODO add your handling code here:
        String Cedula = LbNumCedula.getText();
        
        int IdProyecto = Integer.parseInt(LbIdProyecto.getText());
        
        String notas[] = daoD.buscarDesempeño(Cedula, IdProyecto).getNotasDisciplinarias();
        
        if(!notas[0].equals("") && CbNotas.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Nota Disciplinaria:" + "\n" + 
                    notas[0], "Desempeño", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!notas[1].equals("") && CbNotas.getSelectedIndex() == 1){
            JOptionPane.showMessageDialog(this, "Nota Disciplinaria:" + "\n" + 
                    notas[1], "Desempeño", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!notas[2].equals("") && CbNotas.getSelectedIndex() == 2){
            JOptionPane.showMessageDialog(this, "Nota Disciplinaria:" + "\n" + 
                    notas[2], "Desempeño", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "No hay notas disciplinarias", 
                    "Desempeño", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnMostarNotaActionPerformed

    private void TfFechaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfFechaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfFechaSActionPerformed

    private void TfFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfFechaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfFechaIActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir de Administrar Desempeño?", "EXIT", dialogButton);
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbNotas;
    private javax.swing.JLabel LBFechaIngreso;
    private javax.swing.JLabel LbContadorP;
    private javax.swing.JLabel LbContadorT;
    private javax.swing.JLabel LbDesempeño;
    private javax.swing.JLabel LbFechaSalida;
    private javax.swing.JLabel LbIdDesempeño;
    private javax.swing.JLabel LbIdProyecto;
    private javax.swing.JLabel LbNumC;
    private javax.swing.JLabel LbNumCedula;
    private javax.swing.JLabel LbProyecto;
    private javax.swing.JLabel LbPuesto;
    private javax.swing.JLabel LbSalario;
    private javax.swing.JTextField TfCalificacion;
    private javax.swing.JTextField TfFechaI;
    private javax.swing.JTextField TfFechaS;
    private javax.swing.JTextField TfPuesto;
    private javax.swing.JTextArea TfRazon;
    private javax.swing.JTextField TfSalario;
    private javax.swing.JButton btnActualizarBD;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostarNota;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnProyAnterior;
    private javax.swing.JButton btnSiguienteProy;
    private javax.swing.JButton btnSiguienteTrab;
    private javax.swing.JButton btnTrabAnterior;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    // End of variables declaration//GEN-END:variables
}
