/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DaoProyecto;
import javax.swing.JOptionPane;

/**
 *
 * @author Andreita
 */
    public class FrmProyecto extends javax.swing.JFrame {
    private boolean esNuevo; 
    private DaoProyecto lista = new DaoProyecto();
    int posActual = 0;

    /**
     * Creates new form FrmProyecto
     */
    public FrmProyecto() {
        initComponents();
        mostrarEnTF(0);
    }
    
    public void setDaoP(DaoProyecto dao){
        lista = dao;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TfNombreProyecto = new javax.swing.JTextField();
        LbIdProyecto = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnVolver = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnNuevoT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnGuardarT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEliminarT = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnAnteriorT = new javax.swing.JButton();
        LbContador = new javax.swing.JLabel();
        btnSiguienteT = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnActualizarT = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnModificarP = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROYECTO");
        setLocation(new java.awt.Point(900, 630));
        setMinimumSize(new java.awt.Dimension(900, 630));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRISMA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/prisma-logo-3805665B69-seeklogo.com.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 270, 390));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/70-709970_fondo-morado-oscuro-hd.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 630));

        jPanel2.setBackground(new java.awt.Color(16, 16, 16));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del Proyecto: ");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID: ");

        TfNombreProyecto.setBackground(new java.awt.Color(16, 16, 16));
        TfNombreProyecto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfNombreProyecto.setForeground(new java.awt.Color(78, 34, 88));
        TfNombreProyecto.setBorder(null);

        LbIdProyecto.setBackground(new java.awt.Color(16, 16, 16));
        LbIdProyecto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LbIdProyecto.setForeground(new java.awt.Color(78, 34, 88));

        jToolBar1.setBackground(new java.awt.Color(16, 16, 16));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(32769, 32769));
        jToolBar1.setMinimumSize(new java.awt.Dimension(450, 57));

        btnVolver.setBackground(new java.awt.Color(16, 16, 16));
        btnVolver.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/anterior (1).png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVolver);

        jSeparator6.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator6.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator6);

        btnNuevoT.setBackground(new java.awt.Color(16, 16, 16));
        btnNuevoT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnNuevoT.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/agregar-archivo.png"))); // NOI18N
        btnNuevoT.setText("Nuevo");
        btnNuevoT.setBorder(null);
        btnNuevoT.setFocusable(false);
        btnNuevoT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevoT);
        jToolBar1.add(jSeparator1);

        btnGuardarT.setBackground(new java.awt.Color(16, 16, 16));
        btnGuardarT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnGuardarT.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/disquete.png"))); // NOI18N
        btnGuardarT.setText("Guardar");
        btnGuardarT.setBorder(null);
        btnGuardarT.setFocusable(false);
        btnGuardarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardarT);
        jToolBar1.add(jSeparator2);

        btnEliminarT.setBackground(new java.awt.Color(16, 16, 16));
        btnEliminarT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnEliminarT.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/basura.png"))); // NOI18N
        btnEliminarT.setText("Eliminar");
        btnEliminarT.setBorder(null);
        btnEliminarT.setFocusable(false);
        btnEliminarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarT);
        jToolBar1.add(jSeparator3);

        btnAnteriorT.setBackground(new java.awt.Color(16, 16, 16));
        btnAnteriorT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnAnteriorT.setForeground(new java.awt.Color(255, 255, 255));
        btnAnteriorT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/flecha-izquierda.png"))); // NOI18N
        btnAnteriorT.setText("Anterior");
        btnAnteriorT.setFocusable(false);
        btnAnteriorT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnteriorT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnteriorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnteriorT);

        LbContador.setBackground(new java.awt.Color(255, 255, 255));
        LbContador.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        LbContador.setForeground(new java.awt.Color(255, 255, 255));
        LbContador.setText("0 de 0");
        jToolBar1.add(LbContador);

        btnSiguienteT.setBackground(new java.awt.Color(16, 16, 16));
        btnSiguienteT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSiguienteT.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/flecha-derecha.png"))); // NOI18N
        btnSiguienteT.setText("Siguiente");
        btnSiguienteT.setBorder(null);
        btnSiguienteT.setFocusable(false);
        btnSiguienteT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguienteT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSiguienteT);
        jToolBar1.add(jSeparator4);

        btnActualizarT.setBackground(new java.awt.Color(16, 16, 16));
        btnActualizarT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnActualizarT.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/actualizar.png"))); // NOI18N
        btnActualizarT.setText("Actualizar");
        btnActualizarT.setBorder(null);
        btnActualizarT.setFocusable(false);
        btnActualizarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizarT);
        jToolBar1.add(jSeparator5);

        btnModificarP.setBackground(new java.awt.Color(16, 16, 16));
        btnModificarP.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnModificarP.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/editar.png"))); // NOI18N
        btnModificarP.setText("Modificar");
        btnModificarP.setBorder(null);
        btnModificarP.setFocusable(false);
        btnModificarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificarP);
        jToolBar1.add(jSeparator8);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 34, 88));
        jLabel5.setText("PROYECTO");

        jSeparator7.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator7.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator9.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator9.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator10.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator10.setForeground(new java.awt.Color(78, 34, 88));

        jLabel6.setBackground(new java.awt.Color(78, 34, 88));
        jLabel6.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 34, 88));
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(78, 34, 88));
        jLabel8.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(78, 34, 88));
        jLabel8.setText("-");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TfNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TfNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 530, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTActionPerformed
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_btnNuevoTActionPerformed

    private void btnGuardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTActionPerformed
        // TODO add your handling code here:
        if(TfNombreProyecto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre", "Proyecto",
                    JOptionPane.WARNING_MESSAGE);
            this.TfNombreProyecto.requestFocus();
            return;
        }
        int b;
        if (esNuevo){            
            if(lista.getListaProyecto().isEmpty()){
                b = lista.agregarProyecto(1, TfNombreProyecto.getText());
            }
            else{
                int IdMayor = lista.buscarIdMayor(); // creo que ya esta
                
                b = lista.agregarProyecto(IdMayor + 1, TfNombreProyecto.getText());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Error: Este proyecto ya existe", 
                    "Proyecto", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(b == 1){
            JOptionPane.showMessageDialog(this, "Registro guardado...", "Proyecto",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        this.mostrarEnTF(0);
        limpiar();
    }//GEN-LAST:event_btnGuardarTActionPerformed

    private void btnEliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, 
                "¿Realmente desea eliminar el proyecto " + 
                        this.TfNombreProyecto.getText()+ "?","Proyecto", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (resp == 0){
            int b = lista.eliminarProyecto(Integer.parseInt(LbIdProyecto.getText()));
            if(b==1){
                JOptionPane.showMessageDialog(this, "Registro eliminado satisfactoriamente", 
                        "Proyecto", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error inesperado, verifique y vuelva intentar",
                        "Proyecto", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarTActionPerformed

    private void btnAnteriorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorTActionPerformed
        // TODO add your handling code here:
     if (posActual == 0) posActual = lista.getListaProyecto().size();
        posActual--;
        this.mostrarEnTF(posActual);
    }//GEN-LAST:event_btnAnteriorTActionPerformed

    private void btnSiguienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteTActionPerformed
        // TODO add your handling code here:
        posActual++;
        if (posActual == lista.getListaProyecto().size()) posActual = 0;  
        this.mostrarEnTF(posActual);
    }//GEN-LAST:event_btnSiguienteTActionPerformed

    private void btnActualizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTActionPerformed
        // TODO add your handling code here:
        String msn = lista.actualizarBD();
        JOptionPane.showMessageDialog(this, msn, "Actualizar Base de Datos",
                JOptionPane.INFORMATION_MESSAGE);
        posActual = 0;
        lista = new DaoProyecto();
        mostrarEnTF(posActual);
    }//GEN-LAST:event_btnActualizarTActionPerformed

    private void btnModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPActionPerformed
        // TODO add your handling code here:
        FrmModificarP mod = new FrmModificarP();
        mod.setVisible(true);
        int id = Integer.parseInt(LbIdProyecto.getText());
        mod.setDaoP(lista, id);
        this.dispose();
    }//GEN-LAST:event_btnModificarPActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmInicio ini = new FrmInicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir de Administrar Proyecto?", "EXIT", dialogButton);
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked
    
    private void limpiar(){
        esNuevo = true;
        TfNombreProyecto.setText("");
        LbIdProyecto.setText("");
        TfNombreProyecto.requestFocus();
    }
    private void mostrarEnTF(int fila){
        if(!lista.getListaProyecto().isEmpty() && 
                lista.getListaProyecto().get(fila).getEstado() != 3){
            TfNombreProyecto.setText(lista.getListaProyecto().get(fila).getNombreProyecto());
            LbIdProyecto.setText("" + (lista.getListaProyecto().get(fila).getIdProyecto()));
            
            esNuevo=false;

            int ultReg = lista.getListaProyecto().size();
            LbContador.setText("" + (fila + 1) + " de " + ultReg);
            TfNombreProyecto.requestFocus();
           
        }else{
             limpiar();
             LbContador.setText("" + (0) + " de " + 0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbContador;
    private javax.swing.JLabel LbIdProyecto;
    private javax.swing.JTextField TfNombreProyecto;
    private javax.swing.JButton btnActualizarT;
    private javax.swing.JButton btnAnteriorT;
    private javax.swing.JButton btnEliminarT;
    private javax.swing.JButton btnGuardarT;
    private javax.swing.JButton btnModificarP;
    private javax.swing.JButton btnNuevoT;
    private javax.swing.JButton btnSiguienteT;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
