/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DaoTrabajador;

import javax.swing.JOptionPane;

/**
 *
 * @author Andreita
 */
public class FrmTrabajador extends javax.swing.JFrame {
    DaoTrabajador lista = new DaoTrabajador();
    private boolean esNuevo;
    int posActual = 0;

    /**
     * Creates new form FrmTrabajador
     */
    public FrmTrabajador() {
        initComponents();
        mostrarEnTF(0);
    }
    
    public void setDaoT(DaoTrabajador lista){
        this.lista = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfApellido = new javax.swing.JTextField();
        TfNombre = new javax.swing.JTextField();
        TfNumCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TfSeguroSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnVolver = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnNuevoT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnGuardarT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEliminarT = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnAnteriorT = new javax.swing.JButton();
        LbContador = new javax.swing.JLabel();
        btnSiguienteT = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnActualizarT = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnModificar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TRABAJADOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(900, 630));
        setMaximumSize(new java.awt.Dimension(900, 630));
        setMinimumSize(new java.awt.Dimension(900, 630));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRISMA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/prisma-logo-3805665B69-seeklogo.com.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Pictures\\70-709970_fondo-morado-oscuro-hd.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 630));

        jPanel1.setBackground(new java.awt.Color(16, 16, 16));
        jPanel1.setForeground(new java.awt.Color(78, 34, 88));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N° de Cédula:");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apropiado:");

        TfApellido.setBackground(new java.awt.Color(16, 16, 16));
        TfApellido.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfApellido.setForeground(new java.awt.Color(78, 34, 88));
        TfApellido.setBorder(null);

        TfNombre.setBackground(new java.awt.Color(16, 16, 16));
        TfNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfNombre.setForeground(new java.awt.Color(78, 34, 88));
        TfNombre.setBorder(null);
        TfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreActionPerformed(evt);
            }
        });

        TfNumCedula.setBackground(new java.awt.Color(16, 16, 16));
        TfNumCedula.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfNumCedula.setForeground(new java.awt.Color(78, 34, 88));
        TfNumCedula.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° de Seguro Social: ");

        TfSeguroSocial.setBackground(new java.awt.Color(16, 16, 16));
        TfSeguroSocial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TfSeguroSocial.setForeground(new java.awt.Color(78, 34, 88));
        TfSeguroSocial.setBorder(null);

        jLabel6.setBackground(new java.awt.Color(16, 16, 16));
        jLabel6.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 34, 88));
        jLabel6.setText("Sí");

        jToolBar1.setBackground(new java.awt.Color(16, 16, 16));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnVolver.setBackground(new java.awt.Color(16, 16, 16));
        btnVolver.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/anterior (1).png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setFocusable(false);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVolver);

        jSeparator7.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator7.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator7);

        btnNuevoT.setBackground(new java.awt.Color(16, 16, 16));
        btnNuevoT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnNuevoT.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/agregar-usuario.png"))); // NOI18N
        btnNuevoT.setText("Nuevo");
        btnNuevoT.setBorder(null);
        btnNuevoT.setFocusable(false);
        btnNuevoT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevoT);

        jSeparator1.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator1.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator1);

        btnGuardarT.setBackground(new java.awt.Color(16, 16, 16));
        btnGuardarT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnGuardarT.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/disquete.png"))); // NOI18N
        btnGuardarT.setText("Guardar");
        btnGuardarT.setBorder(null);
        btnGuardarT.setFocusable(false);
        btnGuardarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardarT);

        jSeparator2.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator2.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator2);

        btnEliminarT.setBackground(new java.awt.Color(16, 16, 16));
        btnEliminarT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnEliminarT.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/dejar-de-seguir.png"))); // NOI18N
        btnEliminarT.setText("Eliminar");
        btnEliminarT.setBorder(null);
        btnEliminarT.setFocusable(false);
        btnEliminarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarT);

        jSeparator3.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator3.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator3);

        btnAnteriorT.setBackground(new java.awt.Color(16, 16, 16));
        btnAnteriorT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnAnteriorT.setForeground(new java.awt.Color(255, 255, 255));
        btnAnteriorT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\flecha-izquierda.png")); // NOI18N
        btnAnteriorT.setText("Anterior");
        btnAnteriorT.setBorder(null);
        btnAnteriorT.setFocusable(false);
        btnAnteriorT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnteriorT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnteriorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnteriorT);

        LbContador.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        LbContador.setForeground(new java.awt.Color(255, 255, 255));
        LbContador.setText("0 de 0");
        jToolBar1.add(LbContador);

        btnSiguienteT.setBackground(new java.awt.Color(16, 16, 16));
        btnSiguienteT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSiguienteT.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\flecha-derecha.png")); // NOI18N
        btnSiguienteT.setText("Siguiente");
        btnSiguienteT.setBorder(null);
        btnSiguienteT.setFocusable(false);
        btnSiguienteT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguienteT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSiguienteT);

        jSeparator4.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator4.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator4);

        btnActualizarT.setBackground(new java.awt.Color(16, 16, 16));
        btnActualizarT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnActualizarT.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/actualizar.png"))); // NOI18N
        btnActualizarT.setText("Actualizar");
        btnActualizarT.setBorder(null);
        btnActualizarT.setFocusable(false);
        btnActualizarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizarT);

        jSeparator5.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator5.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator5);

        btnModificar.setBackground(new java.awt.Color(16, 16, 16));
        btnModificar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario/iconos/editar (2).png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificar);

        jSeparator6.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator6.setForeground(new java.awt.Color(78, 34, 88));
        jToolBar1.add(jSeparator6);

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(78, 34, 88));
        jLabel9.setText("Trabajador");

        jSeparator8.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator8.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator9.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator9.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator10.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator10.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator11.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator11.setForeground(new java.awt.Color(78, 34, 88));

        jSeparator12.setBackground(new java.awt.Color(78, 34, 88));
        jSeparator12.setForeground(new java.awt.Color(78, 34, 88));

        jLabel11.setBackground(new java.awt.Color(78, 34, 88));
        jLabel11.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(78, 34, 88));
        jLabel11.setText("-");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(78, 34, 88));
        jLabel12.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(78, 34, 88));
        jLabel12.setText("X");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(TfNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfSeguroSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TfNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfSeguroSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 560, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnNuevoTActionPerformed

    private void btnGuardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTActionPerformed
        // TODO add your handling code here:
        if(TfNombre.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre", 
                    "Trabajador", JOptionPane.WARNING_MESSAGE);
            this.TfNombre.requestFocus();
            return;
        }
        if(TfApellido.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un apellido", 
                    "Trabajador", JOptionPane.WARNING_MESSAGE);
            this.TfApellido.requestFocus();
            return;
        }
        if(TfNumCedula.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número de Cédula",
                    "Trabajador", JOptionPane.WARNING_MESSAGE);
            this.TfNumCedula.requestFocus();
            return;
         }
        if(TfSeguroSocial.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número de Seguro Social",
                    "Trabajador", JOptionPane.WARNING_MESSAGE);
            this.TfSeguroSocial.requestFocus();
            return;
        }
        int b=0;
        if (esNuevo){
            b = lista.agregarTrabajador(TfNombre.getText(), TfApellido.getText(),
                    TfNumCedula.getText(), TfSeguroSocial.getText());
        }
        if(b == 1){
            JOptionPane.showMessageDialog(this, "Registro guardado...", "Trabajador",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Error inesperado...", "Trabajador",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.mostrarEnTF(0);
        limpiar();
    }//GEN-LAST:event_btnGuardarTActionPerformed

    private void btnEliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTActionPerformed
        // TODO add your handling code here:
           int resp = JOptionPane.showConfirmDialog(this, 
                "¿Realmente desea eliminar el Trabajador " + this.TfNombre.getText() + 
                " " + this.TfApellido.getText() + "?", "Trabajador",
                 JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0){
            int b = lista.eliminarTrabajador(TfNumCedula.getText());
            if(b==1){
                JOptionPane.showMessageDialog(this, "Registro eliminado satisfactoriamente"
                , "Trabajador", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error inesperado, verifique y vuelva intentar",
                        "Trabajador", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarTActionPerformed

    private void btnAnteriorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorTActionPerformed
        // TODO add your handling code here:
       if (posActual == 0) posActual = lista.getListaTrabajador().size();
        posActual--;
        this.mostrarEnTF(posActual);
    }//GEN-LAST:event_btnAnteriorTActionPerformed

    private void btnSiguienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteTActionPerformed
        // TODO add your handling code here:
        posActual++;
        if (posActual == lista.getListaTrabajador().size()) posActual = 0;  
        this.mostrarEnTF(posActual);
    }//GEN-LAST:event_btnSiguienteTActionPerformed

    private void btnActualizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTActionPerformed
        // TODO add your handling code here:
        String msn = lista.actualizarBD();
        JOptionPane.showMessageDialog(this, msn, "Actualizar Base de Datos",
                JOptionPane.INFORMATION_MESSAGE);
        posActual =0;
        mostrarEnTF(posActual);
        
        
    }//GEN-LAST:event_btnActualizarTActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        FrmModificarT mod = new FrmModificarT();
        mod.setVisible(true);
        mod.setDaoT(lista, TfNumCedula.getText());
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmInicio ini = new FrmInicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void TfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNombreActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir de Administrar Trabajadores?", "EXIT", dialogButton);
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void mostrarEnTF(int fila){
        if(!lista.getListaTrabajador().isEmpty() &&
                lista.getListaTrabajador().get(fila).getEstado() != 3){
            
            TfNombre.setText(lista.getListaTrabajador().get(fila).getNombres());
            TfApellido.setText(lista.getListaTrabajador().get(fila).getApellidos());
            TfNumCedula.setText(lista.getListaTrabajador().get(fila).getNumCedula());
            TfSeguroSocial.setText(lista.getListaTrabajador().get(fila).getNumSeguroSocial());
            
            esNuevo=false;

            int ultReg = lista.getListaTrabajador().size();
            LbContador.setText("" + (fila + 1) + " de " + ultReg);
            TfNombre.requestFocus();
            System.out.println("check");
        }else{
             limpiar();
             LbContador.setText("" + (0) + " de " + 0);
        }
    }
    private void limpiar(){
        esNuevo = true;
        TfNombre.setText("");
        TfApellido.setText("");
        TfNumCedula.setText("");
        TfSeguroSocial.setText("");
        TfNombre.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbContador;
    private javax.swing.JTextField TfApellido;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JTextField TfNumCedula;
    private javax.swing.JTextField TfSeguroSocial;
    private javax.swing.JButton btnActualizarT;
    private javax.swing.JButton btnAnteriorT;
    private javax.swing.JButton btnEliminarT;
    private javax.swing.JButton btnGuardarT;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoT;
    private javax.swing.JButton btnSiguienteT;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
